version: '3'

services:

  app:
    build: ./
    container_name: 'inside-jwt-app-compose'
    ports:
      - 9000:9000

  postgres:
    image: 'postgres:12'
    container_name: 'postgres-compose'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=5587'
      - 'POSTGRES_DB=insidejwt'
